let texto: string = "Hola mundo";
console.log(texto);
let numero: number = 67;
console.log(numero);
let booleano: boolean = true;
console.log(booleano);
let nulo: null = null;
console.log(nulo);
let indefinido: undefined = undefined;
console.log(indefinido);
